/**
 * Curated Authentic Seed Rules: Classical Western System (William G. Benham)
 * Sourced from: The Laws of Scientific Hand Reading (1900), G.P. Putnam's Sons, New York.
 */

import { KnowledgeRule } from '../ontology/RuleSchema.js';

export const BENHAM_SEED_RULES: KnowledgeRule[] = [
  {
    rule_id: 'benham-head-separated-life-001',
    version: 1,
    feature: 'HEAD_LINE',
    condition_logic: 'AND',
    conditions: [
      { property: 'origin', operator: 'equals', value: 'SEPARATED_FROM_LIFE' },
    ],
    tradition: 'CLASSICAL_WESTERN',
    interpretation: {
      category: 'PERSONALITY',
      headline: 'Independent Initiative and Self-Reliant Confidence',
      traditional_statement: 'Traditional palmistry associates a head line separated at its origin from the life line with early independence of thought, audacity, and self-reliant conviction.',
      detailed_analysis: 'William G. Benham emphasizes that when the Head Line does not touch the Life Line at its commencement under Jupiter, the subject is not tethered by excessive hesitation or family consensus. They trust their own perceptions quickly, act promptly, and possess bold confidence in their ideas.',
      traditional_keywords: ['independence', 'audacity', 'self-confidence', 'separated head line'],
    },
    source_refs: [
      {
        source_id: 'benham-laws-hand-reading-1900',
        source_title: 'The Laws of Scientific Hand Reading (1900)',
        author: 'William G. Benham',
        chapter: 'Chapter: The Line of Head',
        page: 258,
        excerpt: 'When the Line of Head is separated from the Line of Life at its start, it shows self-reliance, promptness in decision, freedom from hesitation, and bold initiative.',
      },
    ],
    evidence_type: 'SOURCE_DIRECT',
    strength: 'PRIMARY',
    status: 'ACTIVE',
    tags: ['head_line', 'independence', 'benham', 'confidence'],
    created_at: '2026-09-18T00:00:00Z',
    updated_at: '2026-09-18T00:00:00Z',
  },
  {
    rule_id: 'benham-head-joined-life-002',
    version: 1,
    feature: 'HEAD_LINE',
    condition_logic: 'AND',
    conditions: [
      { property: 'origin', operator: 'equals', value: 'JOINED_TO_LIFE' },
    ],
    tradition: 'CLASSICAL_WESTERN',
    interpretation: {
      category: 'PERSONALITY',
      headline: 'Deliberate Caution and Methodical Prudence',
      traditional_statement: 'Traditional palmistry associates a head line joined closely to the life line at its origin with careful deliberation, caution, and consideration of consequences.',
      detailed_analysis: 'Benham documents that a joined start indicates prudent forethought and respectful sensitivity to surroundings before stepping forward. The person weighs options methodically rather than leaping headlong.',
      traditional_keywords: ['prudence', 'caution', 'deliberate thinking', 'methodical'],
    },
    source_refs: [
      {
        source_id: 'benham-laws-hand-reading-1900',
        source_title: 'The Laws of Scientific Hand Reading (1900)',
        author: 'William G. Benham',
        chapter: 'Chapter: The Line of Head',
        page: 260,
        excerpt: 'When connected with the Line of Life at the start, it indicates caution, sensitive prudence, and a disposition to weigh steps carefully before acting.',
      },
    ],
    evidence_type: 'SOURCE_DIRECT',
    strength: 'PRIMARY',
    status: 'ACTIVE',
    tags: ['head_line', 'prudence', 'benham', 'methodical'],
    created_at: '2026-09-18T00:00:00Z',
    updated_at: '2026-09-18T00:00:00Z',
  },
  {
    rule_id: 'benham-mount-jupiter-prominent-003',
    version: 1,
    feature: 'MOUNT_JUPITER',
    condition_logic: 'AND',
    conditions: [
      { property: 'prominence', operator: 'equals', value: 'WELL_DEVELOPED' },
      { property: 'firmness', operator: 'equals', value: 'FIRM' },
    ],
    tradition: 'CLASSICAL_WESTERN',
    interpretation: {
      category: 'LEADERSHIP',
      headline: 'Executive Ambition and Natural Leadership Dignity',
      traditional_statement: 'Traditional palmistry associates a well-developed, firm Mount of Jupiter with natural leadership dignity, administrative confidence, and honorable ambition.',
      detailed_analysis: 'Benham ranks the Jupiterian type as having commanding presence, high moral self-respect, sociability, and natural aptitude for organizing and guiding groups toward a vision.',
      traditional_keywords: ['leadership', 'Jupiter mount', 'executive presence', 'ambition'],
    },
    source_refs: [
      {
        source_id: 'benham-laws-hand-reading-1900',
        source_title: 'The Laws of Scientific Hand Reading (1900)',
        author: 'William G. Benham',
        chapter: 'The Mount of Jupiter',
        page: 72,
        excerpt: 'The well-developed Mount of Jupiter bestows ambition, pride, leadership, dignity, and a love of command tempered by natural honor.',
      },
    ],
    evidence_type: 'SOURCE_DIRECT',
    strength: 'PRIMARY',
    status: 'ACTIVE',
    tags: ['mount_jupiter', 'leadership', 'benham', 'ambition'],
    created_at: '2026-09-18T00:00:00Z',
    updated_at: '2026-09-18T00:00:00Z',
  },
  {
    rule_id: 'benham-mount-sun-prominent-004',
    version: 1,
    feature: 'MOUNT_SUN',
    condition_logic: 'AND',
    conditions: [
      { property: 'prominence', operator: 'equals', value: 'WELL_DEVELOPED' },
    ],
    tradition: 'CLASSICAL_WESTERN',
    interpretation: {
      category: 'CREATIVITY',
      headline: 'Artistic Refinement and Warm Aesthetic Charisma',
      traditional_statement: 'Traditional palmistry associates a prominent Mount of the Sun (Apollo) with aesthetic sensibility, refined taste, social magnetism, and a love of beautiful things.',
      detailed_analysis: 'Benham describes Apollonian types as naturally charming, appreciative of harmony, culture, and graceful presentation, radiating sunny cheerfulness.',
      traditional_keywords: ['aesthetics', 'Apollo mount', 'sun', 'artistic taste', 'charm'],
    },
    source_refs: [
      {
        source_id: 'benham-laws-hand-reading-1900',
        source_title: 'The Laws of Scientific Hand Reading (1900)',
        author: 'William G. Benham',
        chapter: 'The Mount of Apollo',
        page: 114,
        excerpt: 'The Apollonian is brilliant, handsome, artistic, loving harmonious environments and having an instinctive taste for color, symmetry, and grace.',
      },
    ],
    evidence_type: 'SOURCE_DIRECT',
    strength: 'PRIMARY',
    status: 'ACTIVE',
    tags: ['mount_sun', 'apollo', 'aesthetics', 'charm'],
    created_at: '2026-09-18T00:00:00Z',
    updated_at: '2026-09-18T00:00:00Z',
  },
  {
    rule_id: 'benham-heart-deep-clear-005',
    version: 1,
    feature: 'HEART_LINE',
    condition_logic: 'AND',
    conditions: [
      { property: 'depth', operator: 'equals', value: 'DEEP' },
      { property: 'continuity', operator: 'equals', value: 'CLEAR' },
    ],
    tradition: 'CLASSICAL_WESTERN',
    interpretation: {
      category: 'RELATIONSHIPS',
      headline: 'Concentrated Emotional Steadfastness and Loyalty',
      traditional_statement: 'Traditional palmistry associates a deep, clearly incised heart line with constancy, focused affection, and emotional resilience.',
      detailed_analysis: 'Benham notes that deep lines reflect focused energy channeled steadily. A deep heart line indicates feelings that are genuine, sincere, and enduring, not easily shaken by passing moods.',
      traditional_keywords: ['loyalty', 'steadfastness', 'deep heart line', 'emotional constancy'],
    },
    source_refs: [
      {
        source_id: 'benham-laws-hand-reading-1900',
        source_title: 'The Laws of Scientific Hand Reading (1900)',
        author: 'William G. Benham',
        chapter: 'The Line of Heart',
        page: 202,
        excerpt: 'A deep, clearly marked Heart Line indicates that the emotional current is concentrated, sincere, and steadfast.',
      },
    ],
    evidence_type: 'SOURCE_DIRECT',
    strength: 'PRIMARY',
    status: 'ACTIVE',
    tags: ['heart_line', 'depth', 'loyalty', 'steadfastness'],
    created_at: '2026-09-18T00:00:00Z',
    updated_at: '2026-09-18T00:00:00Z',
  },
  {
    rule_id: 'benham-head-fork-writer-006',
    version: 1,
    feature: 'HEAD_LINE',
    condition_logic: 'AND',
    conditions: [
      { property: 'forks', operator: 'equals', value: 'PRESENT' },
    ],
    tradition: 'CLASSICAL_WESTERN',
    interpretation: {
      category: 'CREATIVITY',
      headline: 'The "Writer\'s Fork": Dual Practicality and Imaginative Versatility',
      traditional_statement: 'Traditional palmistry associates a distinct fork at the termination of the head line with an intellectual agility that unites practical common sense with creative narrative imagination.',
      detailed_analysis: 'William G. Benham explains that when the Head Line divides into two branches near its end—one heading straight towards Upper Mars and the other dipping towards the Mount of Moon—the subject possesses the rare capacity to dream creatively while grounding ideas in practical execution.',
      traditional_keywords: ["writer's fork", 'versatility', 'creativity and realism', 'head line fork'],
    },
    source_refs: [
      {
        source_id: 'benham-laws-hand-reading-1900',
        source_title: 'The Laws of Scientific Hand Reading (1900)',
        author: 'William G. Benham',
        chapter: 'The Line of Head',
        page: 274,
        excerpt: 'A fork at the termination of the Line of Head gives versatility, diplomacy, literary adaptability, and the power of looking at questions from a dual perspective.',
      },
    ],
    evidence_type: 'SOURCE_DIRECT',
    strength: 'PRIMARY',
    status: 'ACTIVE',
    tags: ['head_line', 'fork', 'writers_fork', 'benham'],
    created_at: '2026-09-18T00:00:00Z',
    updated_at: '2026-09-18T00:00:00Z',
  },
  {
    rule_id: 'benham-life-ascending-jupiter-007',
    version: 1,
    feature: 'LIFE_LINE',
    condition_logic: 'AND',
    conditions: [
      { property: 'branches', operator: 'equals', value: 'ASCENDING_TO_JUPITER' },
    ],
    tradition: 'CLASSICAL_WESTERN',
    interpretation: {
      category: 'CAREER',
      headline: 'Ambitious Vitality and Self-Directed Upward Striving',
      traditional_statement: 'Traditional palmistry associates fine upward branches rising from the life line toward the Mount of Jupiter with early ambition, personal enterprise, and high career aspirations.',
      detailed_analysis: 'Benham documents that branches ascending from the main life stream toward Jupiter indicate an individual who actively channels their vital stamina into progressive self-advancement, leadership responsibility, and purposeful enterprise.',
      traditional_keywords: ['ascending branch', 'Jupiter ambition', 'upward striving', 'vital energy'],
    },
    source_refs: [
      {
        source_id: 'benham-laws-hand-reading-1900',
        source_title: 'The Laws of Scientific Hand Reading (1900)',
        author: 'William G. Benham',
        chapter: 'The Line of Life',
        page: 188,
        excerpt: 'Lines rising from the Line of Life toward the Mount of Jupiter show that ambition, pride, and the desire to excel are leading factors in the life.',
      },
    ],
    evidence_type: 'SOURCE_DIRECT',
    strength: 'PRIMARY',
    status: 'ACTIVE',
    tags: ['life_line', 'branches', 'jupiter', 'ambition'],
    created_at: '2026-09-18T00:00:00Z',
    updated_at: '2026-09-18T00:00:00Z',
  },
];
