/**
 * Curated Authentic Seed Rules: Cheiro's Classical System
 * Sourced from: Cheiro's Language of the Hand (1894), Nichols & Co. London.
 */

import { KnowledgeRule } from '../ontology/RuleSchema.js';

export const CHEIRO_SEED_RULES: KnowledgeRule[] = [
  {
    rule_id: 'cheiro-heart-jupiter-001',
    version: 1,
    feature: 'HEART_LINE',
    condition_logic: 'AND',
    conditions: [
      { property: 'length', operator: 'equals', value: 'LONG' },
      { property: 'curvature', operator: 'equals', value: 'CURVED' },
      { property: 'termination', operator: 'equals', value: 'JUPITER' },
    ],
    tradition: 'CHEIRO_SYSTEM',
    interpretation: {
      category: 'EMOTIONAL_STYLE',
      headline: 'Noble and Idealistic Emotional Devotion',
      traditional_statement: 'Traditional palmistry associates a long, curved heart line terminating upon the Mount of Jupiter with an idealistic, elevated nature in emotional life.',
      detailed_analysis: 'In Cheiro\'s classical framework, when the Line of Heart curves gracefully upward to touch or rise upon the Mount of Jupiter, the emotional nature is elevated by the noble attributes of Jupiter—generosity, pride, ambition, and deep loyalty. Such an individual does not love lightly; their affection is marked by devotion and a desire for high moral standards in their partnerships.',
      traditional_keywords: ['idealism', 'nobility', 'loyalty', 'Jupiter termination', 'elevated sentiment'],
    },
    source_refs: [
      {
        source_id: 'cheiro-language-of-hand-1894',
        source_title: "Cheiro's Language of the Hand (1894)",
        author: 'Cheiro',
        chapter: 'Part II, Chapter II: The Line of Heart',
        page: 58,
        excerpt: 'When the Line of Heart rises on the Mount of Jupiter, it indicates the highest type of love—noble, ambitious, and generous. The subject places the object of their devotion on a pedestal.',
      },
    ],
    evidence_type: 'SOURCE_DIRECT',
    strength: 'PRIMARY',
    status: 'ACTIVE',
    tags: ['heart_line', 'jupiter', 'idealism', 'relationships'],
    created_at: '2026-09-18T00:00:00Z',
    updated_at: '2026-09-18T00:00:00Z',
  },
  {
    rule_id: 'cheiro-heart-saturn-002',
    version: 1,
    feature: 'HEART_LINE',
    condition_logic: 'AND',
    conditions: [
      { property: 'termination', operator: 'equals', value: 'SATURN' },
    ],
    tradition: 'CHEIRO_SYSTEM',
    interpretation: {
      category: 'EMOTIONAL_STYLE',
      headline: 'Reserved and Calculating Sentiment',
      traditional_statement: 'Traditional palmistry associates a heart line terminating under the Mount of Saturn with sobriety, reserve, and a practical approach to affection.',
      detailed_analysis: 'Cheiro notes that termination under the Mount of Saturn infuses emotional feelings with Saturnian restraint, caution, and guardedness. Affections may be genuine, but are tempered by prudence, realism, and a need for emotional safety.',
      traditional_keywords: ['caution', 'restraint', 'sober affection', 'Saturn influence'],
    },
    source_refs: [
      {
        source_id: 'cheiro-language-of-hand-1894',
        source_title: "Cheiro's Language of the Hand (1894)",
        author: 'Cheiro',
        chapter: 'Part II, Chapter II: The Line of Heart',
        page: 60,
        excerpt: 'When it rises from the Mount of Saturn, love is more practical and guarded, tinged with the gravity and introspective sobriety of the Saturnian nature.',
      },
    ],
    evidence_type: 'SOURCE_DIRECT',
    strength: 'PRIMARY',
    status: 'ACTIVE',
    tags: ['heart_line', 'saturn', 'prudence', 'emotional_reserve'],
    created_at: '2026-09-18T00:00:00Z',
    updated_at: '2026-09-18T00:00:00Z',
  },
  {
    rule_id: 'cheiro-head-sloping-moon-003',
    version: 1,
    feature: 'HEAD_LINE',
    condition_logic: 'AND',
    conditions: [
      { property: 'curvature', operator: 'in', value: ['SLOPING', 'CURVED'] },
      { property: 'termination', operator: 'equals', value: 'MOUNT_MOON' },
    ],
    tradition: 'CHEIRO_SYSTEM',
    interpretation: {
      category: 'CREATIVITY',
      headline: 'Imaginative and Conceptual Intellect',
      traditional_statement: 'Traditional palmistry associates a head line that slopes gently toward the Mount of the Moon with strong artistic imagination, conceptual thinking, and narrative sensitivity.',
      detailed_analysis: 'According to Cheiro, a gentle downward inclination of the Line of Head toward the Mount of the Moon directs intellectual faculties toward literature, fine arts, imaginative constructs, and qualitative perception rather than sheer dry mechanics.',
      traditional_keywords: ['imagination', 'artistic mind', 'Mount of Moon', 'narrative faculty'],
    },
    source_refs: [
      {
        source_id: 'cheiro-language-of-hand-1894',
        source_title: "Cheiro's Language of the Hand (1894)",
        author: 'Cheiro',
        chapter: 'Part II, Chapter III: The Line of Head',
        page: 66,
        excerpt: 'When the line slopes slightly towards the Mount of the Moon, it indicates artistic tendencies, love of literature, and a rich imaginative faculty.',
      },
    ],
    evidence_type: 'SOURCE_DIRECT',
    strength: 'PRIMARY',
    status: 'ACTIVE',
    tags: ['head_line', 'moon', 'imagination', 'creativity'],
    created_at: '2026-09-18T00:00:00Z',
    updated_at: '2026-09-18T00:00:00Z',
  },
  {
    rule_id: 'cheiro-head-straight-mars-004',
    version: 1,
    feature: 'HEAD_LINE',
    condition_logic: 'AND',
    conditions: [
      { property: 'curvature', operator: 'equals', value: 'STRAIGHT' },
      { property: 'termination', operator: 'equals', value: 'MARS' },
    ],
    tradition: 'CHEIRO_SYSTEM',
    interpretation: {
      category: 'CAREER',
      headline: 'Analytical Realism and Pragmatic Focus',
      traditional_statement: 'Traditional palmistry associates a straight, level head line terminating across toward Upper Mars with pragmatic reasoning, executive clarity, and logical organization.',
      detailed_analysis: 'Cheiro interprets a straight head line traversing the palm horizontally as the signature of common sense, matter-of-fact judgment, commercial acumen, and linear problem-solving.',
      traditional_keywords: ['logic', 'pragmatism', 'executive clarity', 'straight head line'],
    },
    source_refs: [
      {
        source_id: 'cheiro-language-of-hand-1894',
        source_title: "Cheiro's Language of the Hand (1894)",
        author: 'Cheiro',
        chapter: 'Part II, Chapter III: The Line of Head',
        page: 65,
        excerpt: 'When the Line of Head is straight and even right across the hand, the subject possesses a practical, matter-of-fact intellect and excellent commercial or material judgement.',
      },
    ],
    evidence_type: 'SOURCE_DIRECT',
    strength: 'PRIMARY',
    status: 'ACTIVE',
    tags: ['head_line', 'pragmatism', 'logic', 'business'],
    created_at: '2026-09-18T00:00:00Z',
    updated_at: '2026-09-18T00:00:00Z',
  },
  {
    rule_id: 'cheiro-life-broad-venus-005',
    version: 1,
    feature: 'LIFE_LINE',
    condition_logic: 'AND',
    conditions: [
      { property: 'arc', operator: 'equals', value: 'WIDE' },
      { property: 'continuity', operator: 'equals', value: 'CLEAR' },
    ],
    tradition: 'CHEIRO_SYSTEM',
    interpretation: {
      category: 'LIFE_DIRECTION',
      headline: 'Robust Vital Energy and Warm Appetite for Life',
      traditional_statement: 'Traditional palmistry associates a wide, sweeping life line that sweeps broadly into the palm around the Mount of Venus with abundant physical vitality and hearty social warmth.',
      detailed_analysis: 'In Cheiro\'s observations, giving the Mount of Venus ample room by a sweeping arc indicates hearty stamina, enthusiasm, sociability, and warm emotional resilience.',
      traditional_keywords: ['vitality', 'warmth', 'wide arc', 'generosity of spirit'],
    },
    source_refs: [
      {
        source_id: 'cheiro-language-of-hand-1894',
        source_title: "Cheiro's Language of the Hand (1894)",
        author: 'Cheiro',
        chapter: 'Part II, Chapter IV: The Line of Life',
        page: 75,
        excerpt: 'When it curves widely into the palm, giving a large territory to the Mount of Venus, it denotes robust stamina, warm sympathies, and great love of life.',
      },
    ],
    evidence_type: 'SOURCE_DIRECT',
    strength: 'PRIMARY',
    status: 'ACTIVE',
    tags: ['life_line', 'vitality', 'venus', 'stamina'],
    created_at: '2026-09-18T00:00:00Z',
    updated_at: '2026-09-18T00:00:00Z',
  },
  {
    rule_id: 'cheiro-fate-wrist-saturn-006',
    version: 1,
    feature: 'FATE_LINE',
    condition_logic: 'AND',
    conditions: [
      { property: 'origin', operator: 'equals', value: 'WRIST' },
      { property: 'termination', operator: 'equals', value: 'SATURN' },
      { property: 'strength', operator: 'equals', value: 'CLEAR' },
    ],
    tradition: 'CHEIRO_SYSTEM',
    interpretation: {
      category: 'CAREER',
      headline: 'Strong Individual Vocation and Purpose',
      traditional_statement: 'Traditional palmistry associates a clear fate line rising directly from the wrist toward the Mount of Saturn with clear vocational focus and self-directed determination.',
      detailed_analysis: 'Cheiro writes that a line rising straight from the base of the hand without interruptions indicates an early-defined career path and persistent pursuit of personal purpose.',
      traditional_keywords: ['vocation', 'career determination', 'clear fate line'],
    },
    source_refs: [
      {
        source_id: 'cheiro-language-of-hand-1894',
        source_title: "Cheiro's Language of the Hand (1894)",
        author: 'Cheiro',
        chapter: 'Part II, Chapter V: The Line of Fate',
        page: 82,
        excerpt: 'Rising from the wrist and running straight to Saturn, it shows a life of self-made accomplishment and strong individuality of purpose.',
      },
    ],
    evidence_type: 'SOURCE_DIRECT',
    strength: 'PRIMARY',
    status: 'ACTIVE',
    tags: ['fate_line', 'career', 'saturn', 'vocation'],
    created_at: '2026-09-18T00:00:00Z',
    updated_at: '2026-09-18T00:00:00Z',
  },
  {
    rule_id: 'cheiro-heart-girdle-venus-007',
    version: 1,
    feature: 'HEART_LINE',
    condition_logic: 'AND',
    conditions: [
      { property: 'branches', operator: 'equals', value: 'GIRDLE_OF_VENUS' },
    ],
    tradition: 'CHEIRO_SYSTEM',
    interpretation: {
      category: 'EMOTIONAL_STYLE',
      headline: 'Vibrant Emotional Sensitivity and Aesthetic Temperament',
      traditional_statement: 'Traditional palmistry associates the Girdle of Venus curving above the Heart Line with intense emotional receptivity, mood vibrancy, and high artistic perception.',
      detailed_analysis: 'Cheiro notes that an upper semicircular line across the mounts of Saturn and Sun creates an emotional constitution that experiences both joys and sorrows keenly. It bestows passionate aesthetic enthusiasm and intuitive rapport with others.',
      traditional_keywords: ['Girdle of Venus', 'artistic sensitivity', 'emotional intensity', 'empathy'],
    },
    source_refs: [
      {
        source_id: 'cheiro-language-of-hand-1894',
        source_title: "Cheiro's Language of the Hand (1894)",
        author: 'Cheiro',
        chapter: 'Part II, Chapter VIII: The Girdle of Venus',
        page: 92,
        excerpt: 'The Girdle of Venus denotes an ultra-sensitive nature, intellectual and artistic responsiveness, and deep emotional intensity.',
      },
    ],
    evidence_type: 'SOURCE_DIRECT',
    strength: 'PRIMARY',
    status: 'ACTIVE',
    tags: ['heart_line', 'girdle_of_venus', 'sensitivity', 'cheiro'],
    created_at: '2026-09-18T00:00:00Z',
    updated_at: '2026-09-18T00:00:00Z',
  },
  {
    rule_id: 'cheiro-head-bifurcated-fork-008',
    version: 1,
    feature: 'HEAD_LINE',
    condition_logic: 'AND',
    conditions: [
      { property: 'forks', operator: 'equals', value: 'PRESENT' },
    ],
    tradition: 'CHEIRO_SYSTEM',
    interpretation: {
      category: 'COMMUNICATION',
      headline: 'Diplomatic Dual Mind: Literary Fluency and Persuasive Tact',
      traditional_statement: 'Traditional palmistry associates a clear fork at the terminus of the head line with conversational diplomacy, persuasive debate, and versatile writing skill.',
      detailed_analysis: 'Cheiro considers a well-formed fork on the Line of Head to bestow remarkable dexterity with words and ideas. One prong anchors the intellect in factual Upper Mars reality while the other reaches into the lunar realm of metaphor and storytelling.',
      traditional_keywords: ['diplomacy', 'bifurcated head line', 'literary fluency', 'persuasion'],
    },
    source_refs: [
      {
        source_id: 'cheiro-language-of-hand-1894',
        source_title: "Cheiro's Language of the Hand (1894)",
        author: 'Cheiro',
        chapter: 'Part II, Chapter III: The Line of Head',
        page: 67,
        excerpt: 'When the Line of Head ends in a fine fork, it indicates great mental agility, diplomacy in handling people, and a gift for literature and eloquence.',
      },
    ],
    evidence_type: 'SOURCE_DIRECT',
    strength: 'PRIMARY',
    status: 'ACTIVE',
    tags: ['head_line', 'fork', 'diplomacy', 'eloquence', 'cheiro'],
    created_at: '2026-09-18T00:00:00Z',
    updated_at: '2026-09-18T00:00:00Z',
  },
];
