/**
 * Curated Authentic Seed Rules: Indian Samudrika Shastra & Hastha Rekha Tradition
 * Sourced from: Brihat Samudrika Shastra & Hastha Sanjeevani Classical Canons.
 */

import { KnowledgeRule } from '../ontology/RuleSchema.js';

export const SAMUDRIKA_SEED_RULES: KnowledgeRule[] = [
  {
    rule_id: 'samudrika-hridaya-guru-001',
    version: 1,
    feature: 'HEART_LINE',
    condition_logic: 'AND',
    conditions: [
      { property: 'termination', operator: 'equals', value: 'JUPITER' },
      { property: 'length', operator: 'equals', value: 'LONG' },
    ],
    tradition: 'INDIAN_SAMUDRIKA',
    interpretation: {
      category: 'EMOTIONAL_STYLE',
      headline: 'Dharmic Affection and Devotion to Truth (Satya & Dharma)',
      traditional_statement: 'Traditional Samudrika Shastra associates Hridaya Rekha terminating upon Brihaspati Parvat with noble ethical integrity, righteous devotion (Dharma), and benevolent affection.',
      detailed_analysis: 'In Hastha Rekha scriptures, Guru (Brihaspati) represents wisdom, righteousness, and mentorship. When the heart line concludes clearly on this planetary mount, the native\'s emotional impulses are governed by ethical conscience, family honor, and philanthropic warmth.',
      traditional_keywords: ['Dharma', 'Guru Parvat', 'Brihaspati', 'Hridaya Rekha', 'righteous affection'],
    },
    source_refs: [
      {
        source_id: 'samudrika-shastra-classical',
        source_title: 'Brihat Samudrika Shastra (Hastha Rekha Prakaranam)',
        author: 'Sage Garga / Classical Commentaries',
        chapter: 'Prakarana IV: Hridaya Rekha Lakshanam',
        verse_or_ref: 'Sloka 42-44',
        excerpt: 'Hridaya rekha yadi brihaspati parvatam prapta syat, tada purushah dharmanuragavan, kshamaavan, satyasandhashcha bhavati (When the heart line reaches the mount of Jupiter, the person is devoted to righteousness, forgiving, and committed to truth).',
      },
    ],
    evidence_type: 'SOURCE_DIRECT',
    strength: 'PRIMARY',
    status: 'ACTIVE',
    tags: ['hridaya_rekha', 'guru_parvat', 'dharma', 'samudrika'],
    created_at: '2026-09-18T00:00:00Z',
    updated_at: '2026-09-18T00:00:00Z',
  },
  {
    rule_id: 'samudrika-mati-chandra-002',
    version: 1,
    feature: 'HEAD_LINE',
    condition_logic: 'AND',
    conditions: [
      { property: 'curvature', operator: 'in', value: ['SLOPING', 'CURVED'] },
      { property: 'termination', operator: 'equals', value: 'MOUNT_MOON' },
    ],
    tradition: 'INDIAN_SAMUDRIKA',
    interpretation: {
      category: 'CREATIVITY',
      headline: 'Chandra-Influenced Intuitive & Meditative Intellect (Manas)',
      traditional_statement: 'Traditional Samudrika Shastra associates Mati Rekha sloping toward Chandra Parvat with deep mental sensitivity, poetic imagination, and affinity for sacred or creative learning.',
      detailed_analysis: 'Chandra (the Moon) governs the Manas (sensory and intuitive mind) in Vedic philosophy. When the intellect line leans toward this mount, the thought processes are fluid, reflective, and naturally drawn to intuitive discernment, arts, and metaphysical inquiries.',
      traditional_keywords: ['Mati Rekha', 'Chandra Parvat', 'Manas', 'intuition', 'Vedic psychology'],
    },
    source_refs: [
      {
        source_id: 'samudrika-shastra-classical',
        source_title: 'Brihat Samudrika Shastra',
        author: 'Sage Garga',
        chapter: 'Prakarana V: Mati Rekha Lakshanam',
        verse_or_ref: 'Sloka 19-21',
        excerpt: 'Mati rekha chandra pradeshe nimna gata, kalapriya, bhavuka, sukshma-buddhi-sampannah (When the head line dips towards the lunar realm, the native is an appreciator of arts, emotionally sensitive, and gifted with subtle intellect).',
      },
    ],
    evidence_type: 'SOURCE_DIRECT',
    strength: 'PRIMARY',
    status: 'ACTIVE',
    tags: ['mati_rekha', 'chandra', 'intuition', 'vedic'],
    created_at: '2026-09-18T00:00:00Z',
    updated_at: '2026-09-18T00:00:00Z',
  },
  {
    rule_id: 'samudrika-shukra-prominent-003',
    version: 1,
    feature: 'MOUNT_VENUS',
    condition_logic: 'AND',
    conditions: [
      { property: 'prominence', operator: 'equals', value: 'WELL_DEVELOPED' },
    ],
    tradition: 'INDIAN_SAMUDRIKA',
    interpretation: {
      category: 'LIFE_DIRECTION',
      headline: 'Abundance of Ojas (Vital Essence) and Bhoga-Sukha (Sensory Joy)',
      traditional_statement: 'Traditional Samudrika Shastra associates an elevated, clean Shukra Parvat with abundant physical vitality (Ojas), joyful social relations, and appreciation of earthly beauty.',
      detailed_analysis: 'Shukra (Venus) governs reproductive vitality, grace, refined hospitality, and aesthetic enjoyment. A well-elevated mount reflects vitality and natural warmth that draws affection and domestic harmony.',
      traditional_keywords: ['Shukra Parvat', 'Ojas', 'Sukha', 'sensory harmony', 'Samudrika'],
    },
    source_refs: [
      {
        source_id: 'samudrika-shastra-classical',
        source_title: 'Brihat Samudrika Shastra',
        author: 'Narada Samhita Recension',
        chapter: 'Prakarana II: Parvata Vichara',
        verse_or_ref: 'Sloka 33-35',
        excerpt: 'Utsadite shukra parvatah saumanasya-kartaa, bhogavan, arogyavan (An elevated Mount of Venus grants cheerfulness of mind, worldly comfort, and radiant health).',
      },
    ],
    evidence_type: 'SOURCE_DIRECT',
    strength: 'PRIMARY',
    status: 'ACTIVE',
    tags: ['shukra_parvat', 'ojas', 'vitality', 'samudrika'],
    created_at: '2026-09-18T00:00:00Z',
    updated_at: '2026-09-18T00:00:00Z',
  },
  {
    rule_id: 'samudrika-bhagya-chandra-004',
    version: 1,
    feature: 'FATE_LINE',
    condition_logic: 'AND',
    conditions: [
      { property: 'origin', operator: 'equals', value: 'MOUNT_MOON' },
      { property: 'strength', operator: 'equals', value: 'CLEAR' },
    ],
    tradition: 'INDIAN_SAMUDRIKA',
    interpretation: {
      category: 'CAREER',
      headline: 'Success Through Public Goodwill and Unconventional Support (Loka-Kripa)',
      traditional_statement: 'Traditional Samudrika Shastra associates Bhagya Rekha rising from Chandra Parvat with career ascent catalyzed by public appreciation, mentors outside one\'s birthplace, and supportive partnerships.',
      detailed_analysis: 'Unlike a fate line rising from one\'s own lineage roots, origin on Chandra indicates prosperity fostered through interactions with the wider public, travelers, or allies outside immediate kinship.',
      traditional_keywords: ['Bhagya Rekha', 'Chandra origin', 'Loka-kripa', 'public support'],
    },
    source_refs: [
      {
        source_id: 'samudrika-shastra-classical',
        source_title: 'Hastha Sanjeevani',
        author: 'Traditional Recension',
        chapter: 'Urdhva Rekha Nirupanam',
        verse_or_ref: 'Verse 14',
        excerpt: 'Chandraat samutthitaa rekha yadi shani mandalam vrajet, parar-deshe parajanebhya labho bhavati (A line rising from Moon and journeying to Saturn brings prosperity through distant places and the goodwill of others).',
      },
    ],
    evidence_type: 'SOURCE_DIRECT',
    strength: 'PRIMARY',
    status: 'ACTIVE',
    tags: ['bhagya_rekha', 'chandra', 'career', 'samudrika'],
    created_at: '2026-09-18T00:00:00Z',
    updated_at: '2026-09-18T00:00:00Z',
  },
  {
    rule_id: 'samudrika-guru-prominent-005',
    version: 1,
    feature: 'MOUNT_JUPITER',
    condition_logic: 'AND',
    conditions: [
      { property: 'prominence', operator: 'equals', value: 'WELL_DEVELOPED' },
    ],
    tradition: 'INDIAN_SAMUDRIKA',
    interpretation: {
      category: 'LEADERSHIP',
      headline: 'Guru Anugraha: Revered Authority and Moral Wisdom',
      traditional_statement: 'Traditional Samudrika Shastra associates a prominent Brihaspati (Guru) Parvat with high respect in society, natural advisory capacity, and moral authority.',
      detailed_analysis: 'Brihaspati is the Devaguru (preceptor of celestials). Prominence under the Tarjani (index finger) traditionally marks someone whose counsel is respected by peers and who carries natural dignity in group affairs.',
      traditional_keywords: ['Brihaspati', 'Guru', 'moral authority', 'Tarjani'],
    },
    source_refs: [
      {
        source_id: 'samudrika-shastra-classical',
        source_title: 'Brihat Samudrika Shastra',
        author: 'Sage Garga',
        chapter: 'Prakarana II: Parvata Vichara',
        verse_or_ref: 'Sloka 12-14',
        excerpt: 'Brihaspati samunnata pradeshe naranam jnanavan, kshatriyavat pratapavan, sabhajitah (Elevated Jupiter mount makes the person knowledgeable, influential like a noble leader, and honored in gatherings).',
      },
    ],
    evidence_type: 'SOURCE_DIRECT',
    strength: 'PRIMARY',
    status: 'ACTIVE',
    tags: ['guru_parvat', 'brihaspati', 'wisdom', 'leadership'],
    created_at: '2026-09-18T00:00:00Z',
    updated_at: '2026-09-18T00:00:00Z',
  },
  {
    rule_id: 'samudrika-angustha-logic-will-006',
    version: 1,
    feature: 'THUMB',
    condition_logic: 'AND',
    conditions: [
      { property: 'proportions', operator: 'equals', value: 'BALANCED' },
    ],
    tradition: 'INDIAN_SAMUDRIKA',
    interpretation: {
      category: 'PERSONALITY',
      headline: 'Harmonious Ichha (Will) and Tarka (Logic) Balance',
      traditional_statement: 'Traditional Samudrika Shastra associates an evenly proportioned thumb phalanx configuration with an equilibrium between resolute willpower and reflective logic.',
      detailed_analysis: 'The upper phalanx corresponds to Ichha Shakti (volition and decisive momentum) while the second phalanx corresponds to Tarka Shakti (reasoning and discernment). Symmetrical balance indicates a mind that neither acts recklessly without reasoning nor overthinks into paralysis.',
      traditional_keywords: ['Angustha', 'Ichha Shakti', 'Tarka', 'volition', 'balance'],
    },
    source_refs: [
      {
        source_id: 'samudrika-shastra-classical',
        source_title: 'Brihat Samudrika Shastra',
        author: 'Sage Garga',
        chapter: 'Prakarana I: Angustha Lakshanam',
        verse_or_ref: 'Sloka 5-7',
        excerpt: 'Sama-vibhage hyangusthe tarka-sankalpa-yutah prabhuh (With equal divisions of the thumb, the native possesses both acute reasoning and decisive resolve).',
      },
    ],
    evidence_type: 'SOURCE_DIRECT',
    strength: 'PRIMARY',
    status: 'ACTIVE',
    tags: ['thumb', 'ichha', 'tarka', 'samudrika'],
    created_at: '2026-09-18T00:00:00Z',
    updated_at: '2026-09-18T00:00:00Z',
  },
  {
    rule_id: 'samudrika-budha-prominent-007',
    version: 1,
    feature: 'MOUNT_MERCURY',
    condition_logic: 'AND',
    conditions: [
      { property: 'prominence', operator: 'equals', value: 'WELL_DEVELOPED' },
    ],
    tradition: 'INDIAN_SAMUDRIKA',
    interpretation: {
      category: 'COMMUNICATION',
      headline: 'Budha Prabhav: Eloquent Speech and Commercial Agility',
      traditional_statement: 'Traditional Samudrika Shastra associates an elevated Budha Parvat with quick wit, persuasive speech, mathematical aptitude, and commercial perception.',
      detailed_analysis: 'Budha (Mercury) governs speech (Vak), commerce (Vanijya), and intellectual agility. An elevated mount under the Kanishthika (little finger) indicates talent in communication, diplomacy, and astute commercial strategy.',
      traditional_keywords: ['Budha Parvat', 'Vanijya', 'Vak', 'eloquence', 'Mercury mount'],
    },
    source_refs: [
      {
        source_id: 'samudrika-shastra-classical',
        source_title: 'Brihat Samudrika Shastra',
        author: 'Sage Garga',
        chapter: 'Prakarana II: Parvata Vichara',
        verse_or_ref: 'Sloka 27-29',
        excerpt: 'Budha-sthane samunnate vanik-kushalah, madhura-bhashi, vidyavan (When Mercury mount is elevated, the native is skilled in trade, sweet of speech, and learned).',
      },
    ],
    evidence_type: 'SOURCE_DIRECT',
    strength: 'PRIMARY',
    status: 'ACTIVE',
    tags: ['budha_parvat', 'communication', 'commerce', 'samudrika'],
    created_at: '2026-09-18T00:00:00Z',
    updated_at: '2026-09-18T00:00:00Z',
  },
  {
    rule_id: 'samudrika-surya-rekha-008',
    version: 1,
    feature: 'SUN_LINE',
    condition_logic: 'AND',
    conditions: [
      { property: 'strength', operator: 'in', value: ['CLEAR', 'DEEP', 'PRESENT'] },
    ],
    tradition: 'INDIAN_SAMUDRIKA',
    interpretation: {
      category: 'CREATIVITY',
      headline: 'Surya Kirti: Radiant Acclaim and High Cultural Distinction',
      traditional_statement: 'Traditional Samudrika Shastra associates a prominent Surya Rekha with widespread public goodwill, cultural refinement, and celebrated artistic or scholarly renown.',
      detailed_analysis: 'Surya (Sun) bestows illumination, honor, and magnetic presence. An unbroken Vidya/Surya Rekha indicates that one\'s inner creative talents and knowledge gain visible recognition and social respect.',
      traditional_keywords: ['Surya Rekha', 'Vidya Rekha', 'Kirti', 'public acclaim', 'cultural stature'],
    },
    source_refs: [
      {
        source_id: 'samudrika-shastra-classical',
        source_title: 'Hastha Sanjeevani',
        author: 'Traditional Recension',
        chapter: 'Surya Rekha Varnanam',
        verse_or_ref: 'Sloka 18',
        excerpt: 'Surya rekha supushta yadi shobhate, sarvaloka-priyo vidvan kirtimaan bhavati dhruvam (If the Sun line is well formed, the person is cherished by society, learned, and gains enduring renown).',
      },
    ],
    evidence_type: 'SOURCE_DIRECT',
    strength: 'PRIMARY',
    status: 'ACTIVE',
    tags: ['surya_rekha', 'creativity', 'renown', 'samudrika'],
    created_at: '2026-09-18T00:00:00Z',
    updated_at: '2026-09-18T00:00:00Z',
  },
];
